import type { Metadata } from "next";
import {ThemeProvider} from "@/styles";
import GlobalStyle from "@/styles/GlobalStyle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <html lang="en">
        <body>
          <ThemeProvider>
            <GlobalStyle />
            {children}
          </ThemeProvider>
        </body>
      </html>
  );
}
